CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "WeatherSummaries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    "Summary" character varying(100) NOT NULL,
    "CreatedDt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WeatherSummaries" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250723222141_InitMigration', '9.0.7');

COMMIT;

